// Copies the committed Blender build output into public/ so Vite serves it in
// dev and copies it into dist/ on build. The canonical .glb files live in
// assets/models/dist at the repo root and are authored by tools/blender; the
// web client CONSUMES them and never edits them (ASSET-SPECS.md section 5).
// public/assets is gitignored: one canonical copy, never two.
//
// TEXTURES NOW SHIP (DW-35). The note that used to sit here said section 2.8
// defers a texture pipeline until the payload crosses 1 MB and that every
// asset was untextured PBR roles. Both halves are out of date: two shared
// tiling map sets live in assets/textures/dist, generated by
// tools/blender/texgen.py, and every .glb now carries UVs. The payload is
// 0.59 MB, still under that 1 MB threshold, so there is still no
// gltf-transform / KTX2 step and the whole set is still inside the 25 MB
// critical-preload budget. Revisit KTX2 when the texture payload crosses 1 MB;
// the meshopt half is still worth having then.
//
// The maps are NOT embedded in the .glb files and must not be: 48 assets share
// two textures, and MachineBatch discards per-file materials anyway. See
// tools/blender/surface_preview.py for the whole argument.
import { copyFileSync, mkdirSync, readdirSync, statSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..', 'assets');
const dst = join(here, '..', 'public', 'assets');

// [source, destination, extensions]. Models flatten `models/dist` away, so
// assets/models/dist/machines/miner.glb is served at assets/machines/miner.glb.
// Textures land in their own folder so a map can never collide with a Vite
// chunk name in dist/assets.
const ROOTS = [
  [join(root, 'models', 'dist'), dst, ['.glb']],
  [join(root, 'textures', 'dist'), join(dst, 'textures'), ['.png', '.json']],
];

for (const [src] of ROOTS) {
  if (!existsSync(src)) {
    console.error(`sync-assets: ${src} is missing. Run the Blender build first `
      + `(models: tools/blender/build_*.py, textures: tools/blender/texgen.py).`);
    process.exit(1);
  }
}

const tally = new Map();
function walk(from, to, exts) {
  mkdirSync(to, { recursive: true });
  for (const e of readdirSync(from)) {
    const p = join(from, e);
    if (statSync(p).isDirectory()) { walk(p, join(to, e), exts); continue; }
    const ext = exts.find((x) => e.endsWith(x));
    if (ext === undefined) continue;
    copyFileSync(p, join(to, e));
    const t = tally.get(ext) ?? { files: 0, bytes: 0 };
    t.files++;
    t.bytes += statSync(p).size;
    tally.set(ext, t);
  }
}
for (const [src, to, exts] of ROOTS) walk(src, to, exts);

// Report every extension separately. One combined "N files, M MB" would have
// hidden the texture payload inside the model payload, which is exactly the
// number this pass has to be held to.
const parts = [...tally.entries()].sort()
  .map(([ext, t]) => `${t.files} ${ext}, ${(t.bytes / 1048576).toFixed(2)} MB`);
const total = [...tally.values()].reduce((a, t) => a + t.bytes, 0);
console.log(`sync-assets: ${parts.join(' | ')} | total `
  + `${(total / 1048576).toFixed(2)} MB -> ${relative(join(here, '..'), dst)}`);
