// Copies the committed Blender build output into public/ so Vite serves it in
// dev and copies it into dist/ on build. The canonical .glb files live in
// assets/models/dist at the repo root and are authored by tools/blender; the
// web client CONSUMES them and never edits them (ASSET-SPECS.md section 5).
// public/assets is gitignored: one canonical copy, never two.
//
// TEXTURES NOW SHIP (DW-35). The note that used to sit here said section 2.8
// defers a texture pipeline until the payload crosses 1 MB and that every
// asset was untextured PBR roles. Both halves are out of date: two shared
// tiling map sets live in assets/textures/dist, generated by
// tools/blender/texgen.py, and every .glb now carries UVs. The payload is
// 0.59 MB, still under that 1 MB threshold, so there is still no
// gltf-transform / KTX2 step and the whole set is still inside the 25 MB
// critical-preload budget. Revisit KTX2 when the texture payload crosses 1 MB;
// the meshopt half is still worth having then.
//
// The maps are NOT embedded in the .glb files and must not be: 48 assets share
// two textures, and MachineBatch discards per-file materials anyway. See
// tools/blender/surface_preview.py for the whole argument.
import { copyFileSync, mkdirSync, readdirSync, statSync, existsSync, openSync, readSync, closeSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

// THE POINTER GUARD (BT-60). Git LFS pointers are 130-byte ASCII files that
// begin with this line. Without a smudge filter for their path they check out
// as that TEXT, and this script cheerfully copied 25 of them into public/ and
// reported `25 .png, 0.00 MB`. The app then fetched them with HTTP 200 and a
// content-type of image/png, so the only symptom was a texture decode error
// three layers away, which read like a GPU fault and was diagnosed as one for
// a day. The size WAS printed and nobody read it; this makes it a hard stop.
const LFS_MAGIC = 'version https://git-lfs.github.com/spec/v1';
function lfsPointer(file) {
  // A pointer is always well under 1 KB, so anything larger cannot be one and
  // does not need to be opened.
  if (statSync(file).size > 1024) return false;
  const fd = openSync(file, 'r');
  const buf = Buffer.alloc(LFS_MAGIC.length);
  try { readSync(fd, buf, 0, buf.length, 0); } finally { closeSync(fd); }
  return buf.toString('latin1') === LFS_MAGIC;
}

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..', 'assets');
const dst = join(here, '..', 'public', 'assets');

// [source, destination, extensions]. Models flatten `models/dist` away, so
// assets/models/dist/machines/miner.glb is served at assets/machines/miner.glb.
// Textures land in their own folder so a map can never collide with a Vite
// chunk name in dist/assets.
const ROOTS = [
  [join(root, 'models', 'dist'), dst, ['.glb']],
  [join(root, 'textures', 'dist'), join(dst, 'textures'), ['.png', '.json']],
];

for (const [src] of ROOTS) {
  if (!existsSync(src)) {
    console.error(`sync-assets: ${src} is missing. Run the Blender build first `
      + `(models: tools/blender/build_*.py, textures: tools/blender/texgen.py).`);
    process.exit(1);
  }
}

const tally = new Map();
const pointers = [];
function walk(from, to, exts) {
  mkdirSync(to, { recursive: true });
  for (const e of readdirSync(from)) {
    const p = join(from, e);
    if (statSync(p).isDirectory()) { walk(p, join(to, e), exts); continue; }
    const ext = exts.find((x) => e.endsWith(x));
    if (ext === undefined) continue;
    // Collect every offender before reporting: "one file is a pointer" sends
    // someone hunting one file, "all 25 are" names the real condition.
    if (lfsPointer(p)) { pointers.push(relative(join(here, '..', '..'), p)); continue; }
    copyFileSync(p, join(to, e));
    const t = tally.get(ext) ?? { files: 0, bytes: 0 };
    t.files++;
    t.bytes += statSync(p).size;
    tally.set(ext, t);
  }
}
for (const [src, to, exts] of ROOTS) walk(src, to, exts);

if (pointers.length > 0) {
  console.error(
    `sync-assets: ${pointers.length} source asset(s) are Git LFS POINTER FILES, `
    + `not content. They were NOT copied, because serving 130 bytes of ASCII as `
    + `image/png fails at texture decode and blames the renderer.\n`
    + pointers.map((f) => `  ${f}`).join('\n')
    + `\n\nFix it with:  git lfs pull\n`
    + `If that leaves them as pointers, this clone has no smudge filter for `
    + `their path: check .gitattributes has an explicit filter=lfs rule for `
    + `them (the blanket *.png rule was retired 2026-08-03).`);
  process.exit(1);
}

// Report every extension separately. One combined "N files, M MB" would have
// hidden the texture payload inside the model payload, which is exactly the
// number this pass has to be held to.
const parts = [...tally.entries()].sort()
  .map(([ext, t]) => `${t.files} ${ext}, ${(t.bytes / 1048576).toFixed(2)} MB`);
const total = [...tally.values()].reduce((a, t) => a + t.bytes, 0);
console.log(`sync-assets: ${parts.join(' | ')} | total `
  + `${(total / 1048576).toFixed(2)} MB -> ${relative(join(here, '..'), dst)}`);

// KTX2 TRANSCODER (RN-1462, A2a). The two Basis Universal transcoder files
// (`basis_transcoder.js`/`.wasm`) ship INSIDE three's own npm package, not
// under `assets/` and not from a CDN: the served build is LAN (CLAUDE.md), so
// `KTX2Loader.setTranscoderPath` must point at a same-origin path, and npm
// rather than git LFS is what delivers these bytes, so the pointer guard
// above does not apply to them. Staged the same way every other served asset
// is: `predev`/`prebuild` already run this script before `vite`.
const basisSrc = join(here, '..', 'node_modules', 'three', 'examples', 'jsm', 'libs', 'basis');
const basisDst = join(dst, 'basis');
const BASIS_FILES = ['basis_transcoder.js', 'basis_transcoder.wasm'];
if (!existsSync(basisSrc)) {
  console.error(`sync-assets: ${basisSrc} is missing. Run \`npm ci\` in web/ `
    + 'first; three ships the KTX2 transcoder inside its own package and '
    + 'this script does not fetch it from anywhere else.');
  process.exit(1);
}
mkdirSync(basisDst, { recursive: true });
let basisBytes = 0;
for (const f of BASIS_FILES) {
  const p = join(basisSrc, f);
  if (!existsSync(p)) {
    console.error(`sync-assets: ${p} is missing from the installed three `
      + `package. Expected both of ${BASIS_FILES.join(', ')}.`);
    process.exit(1);
  }
  copyFileSync(p, join(basisDst, f));
  basisBytes += statSync(p).size;
}
console.log(`sync-assets: ${BASIS_FILES.length} basis (KTX2 transcoder), `
  + `${(basisBytes / 1048576).toFixed(2)} MB -> ${relative(join(here, '..'), basisDst)}`);
