// GP-104 / GP-105. THE TWO FLIGHT CHEATS: full tanks, and a stable orbit.
//
// They live beside FlightSession rather than inside it for the same reason
// FlightSas.ts does: that file is four lines under a hard 400-line cap and this
// is not the work to spend them on. They live beside it rather than in the app
// layer for a much better reason: `status`, `metS`, `liftedOff` and the cached
// `st`/`tm`/`orb` rows are INVARIANTS OF A FLIGHT, and a cheat written from the
// outside would push pos/vel through the public `V` handle and leave every
// instrument downstream -- navball, map, `distanceToVessel`, `altitudeAglM` --
// describing a rocket that is no longer there.
//
// NEITHER OF THESE PRETENDS TO BE A FEATURE. `DebugFlight.ts` states the house
// rule that every entry there goes through the player's own path, "no setter
// that puts a vessel in an orbit it did not fly to". This file is the declared
// exception to that rule and is named so it cannot be mistaken for anything
// else. It is reachable only from the pause menu's TESTING section and from
// `__of.cheat`, and in survival using either marks the save (GP-102).

import { SAS_OFF, cross, flightParts, len, norm } from './FlightAbi.js';
import { horizonFrame } from './FlightAttitude.js';
import type { FlightSession } from './FlightSession.js';

/**
 * HOW MUCH PROPELLANT IS ABOARD RIGHT NOW, re-read from /core.
 *
 * `FlightSession.propellantKg()` sums the cached `partRows`, and those are only
 * refreshed by `refreshParts`, which runs on a roll-out and on a staging and at
 * no other time. So the session's own number is the amount the craft held when
 * it was last staged and does NOT move while an engine burns. That is correct
 * for what it is used for elsewhere (a stage table is about the design), and it
 * is completely wrong as a trigger for a top-up: the first version of the cheat
 * read it, saw a number that never fell, and refilled exactly once. The probe
 * caught it as a burn that spent 2190 kg and reported 2190 kg afterwards.
 */
export function livePropellantKg(s: FlightSession): number {
  if (s.handle <= 0) return 0;
  let kg = 0;
  for (const p of flightParts(s.core, s.handle)) kg += p.propellantKg;
  return kg;
}

/**
 * GP-104. REFILL EVERY TANK, by rebuilding the craft from its own design and
 * replaying the stagings.
 *
 * THIS IS NOT THE IMPLEMENTATION ANYONE WOULD CHOOSE, and the reason is stated
 * rather than hidden: /core publishes no propellant setter. The whole `of_fl_*`
 * surface is read-only about fuel -- `_of_fl_parts` copies `propellantKg` out
 * into the scratch arena and nothing writes it back -- and the JS
 * `FlightPartRow` copies are regenerated by `refreshParts`, so writing to those
 * changes a readout and nothing else. The honest fix is one new export; it was
 * not taken tonight because a wasm rebuild would have swept two other lanes'
 * uncommitted `of_*_api.inc` work into the binary, and it is raised to Admin as
 * a dependency instead.
 *
 * WHAT THE REBUILD COSTS, said out loud: the integrator's own `state.timeS`
 * restarts at zero, because a new `FlightSim` is a new clock. Everything a
 * player or a probe can see is carried across explicitly below -- position,
 * velocity, attitude, angular velocity, throttle, SAS mode, SAS command, and
 * which parts are still attached. The stagings are REPLAYED rather than
 * remembered, off the same design's own stage table, so a craft that has thrown
 * away two stages throws away the same two and comes back with the same part
 * count. That last equality is what the probe asserts, because a rebuild that
 * quietly restored the jettisoned stages would refill the tanks perfectly and
 * be completely wrong.
 *
 * Returns the kilograms restored, or -1 when there is nothing to refill.
 */
export function refillTanks(s: FlightSession, bodyHandle: number): number {
  if (s.handle <= 0 || s.design <= 0) return -1;
  const before = livePropellantKg(s);
  const st = s.state;
  const thr = s.throttleValue;
  const staged = s.stagings;
  const h = s.V._of_fl_create(s.design, bodyHandle);
  if (h <= 0) return -1;
  const old = s.handle;
  s.handle = h;
  for (let i = 0; i < staged; ++i) s.V._of_fl_stage(h);
  s.V._of_fl_set_pos_vel(h, st.pos[0], st.pos[1], st.pos[2],
    st.vel[0], st.vel[1], st.vel[2]);
  s.V._of_fl_set_attitude(h, st.forward[0], st.forward[1], st.forward[2],
    st.right[0], st.right[1], st.right[2]);
  s.V._of_fl_set_ang_vel(h, st.angVel[0], st.angVel[1], st.angVel[2]);
  s.V._of_fl_set_throttle(h, thr);
  s.V._of_fl_set_sas(h, s.sasMode);
  s.V._of_fl_set_sas_command(h, s.command[0], s.command[1], s.command[2]);
  s.V._of_fl_destroy(old);
  // Re-reads the tree AND re-samples, which is what puts `st`/`tm`/`orb` onto
  // the new handle, and bumps the revision so `FlightMode` rebuilds the drawn
  // craft rather than leaving meshes bound to a destroyed flight.
  s.refreshParts();
  s.stagings = staged;
  return livePropellantKg(s) - before;
}

/**
 * GP-105. PUT THE CRAFT IN A CIRCULAR ORBIT of radius `radiusM` over the ground
 * it is currently above, travelling east at `speedMS`.
 *
 * THE TWO NUMBERS COME FROM THE CALLER, and that is deliberate: the client
 * already has exactly one authority on the body's radius and mu (`PlanetBody`,
 * off `_of_body_radius` and `_of_body_mu`), and an orbit computed here off a
 * second copy would be a beautiful ellipse around a planet with different
 * physics from the one the rocket then flies in. `Cheats.ts` derives them, from
 * that one authority, as r = R + alt and v = sqrt(mu / r).
 *
 * FOUR PIECES OF SESSION STATE MOVE WITH IT, and every one is a bug found by
 * reading `FlightSession.step` rather than by running it:
 *
 *   `status` must leave CLAMPED, because `stepClamped` restores the CACHED
 *   position and zeroes the velocity, so a teleport out of a clamp would be
 *   silently undone on the very next tick with nothing on screen to say why.
 *
 *   `metS` must leave -1, because `step` adds to it, and a mission elapsed time
 *   of minus one second is a permanent instrument fault.
 *
 *   `liftedOff` must be true, or the arrest branch cannot fire when the player
 *   eventually comes down, and they would fall through the planet.
 *
 *   The clamp must be recorded as RELEASED, because `FlightPad.stepPadClamps`
 *   swings the arms back on `releases > 0 && !clamped`, and four arms closed
 *   around an empty pad is exactly the thing that gets reported as a bug the
 *   next morning.
 *
 * It sets COAST and not ORBIT, deliberately. `step` computes the status from
 * /core's own `inSpace` / `bound` / `periapsisAltM`, so letting it promote the
 * craft on the next tick means the ORBIT the HUD reads is /core's verdict on
 * the state, not this function's claim about what it just wrote. If /core says
 * COAST, the cheat got the arithmetic wrong and the screen says so.
 *
 * The caller is still responsible for `observer.syncToVessel()`: the camera's
 * interpolator belongs to the observer, and without it the eye lerps across
 * 600 km in a single frame.
 */
export function warpToOrbit(s: FlightSession, radiusM: number,
                            speedMS: number): boolean {
  if (s.handle <= 0 || !(radiusM > 0) || !(speedMS > 0)) return false;
  const u = len(s.state.pos) > 1 ? norm(s.state.pos) : norm(s.padUp);
  const east = horizonFrame(u).east;
  s.V._of_fl_set_pos_vel(s.handle, u[0] * radiusM, u[1] * radiusM, u[2] * radiusM,
    east[0] * speedMS, east[1] * speedMS, east[2] * speedMS);
  // Nose PROGRADE, which is where a craft that got here by flying would be
  // pointing, and the only attitude from which the next burn means anything.
  const right = norm(cross(east, u));
  s.V._of_fl_set_attitude(s.handle, east[0], east[1], east[2],
    right[0], right[1], right[2]);
  s.V._of_fl_set_ang_vel(s.handle, 0, 0, 0);
  // THE THROTTLE IS SHUT, and that is part of the verb rather than tidiness.
  // The player asked for a STABLE orbit; arriving in one with the engine still
  // lit means the very next tick starts raising the apoapsis, and the probe
  // measured exactly that before this line existed: e = 0.15994 and 266 km
  // between apoapsis and periapsis, three seconds after a teleport that had
  // written a perfectly circular state.
  s.setThrottle(0);
  if (s.status === 'CLAMPED') { s.releases += 1; s.releasedAtTick = s.fixedTick; }
  s.status = 'COAST';
  if (!(s.metS >= 0)) s.metS = 0;
  s.liftedOff = true;
  s.warpIndex = 0;
  s.sasMode = SAS_OFF;
  s.commandDirection(east);
  s.sample();
  // The altitude on the line is read back off TELEMETRY after the re-sample,
  // never computed here from a body radius: this file deliberately holds no
  // second copy of the planet, which is the whole reason `radiusM` and
  // `speedMS` arrive as arguments.
  s.flash(`teleported to a ${(s.telemetry.altitudeM / 1000).toFixed(0)} km orbit`);
  return true;
}
